name: Release

on:
  push:
    branches: [main, beta, alpha]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0

      - name: 'Setup Java'
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: 'Setup Node'
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: lts/*

      - name: Build & test
        run: mvn -B -ntp verify

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install --no-save semantic-release \
            @semantic-release/git \
            @semantic-release/exec \
            @semantic-release/github \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator
            
          npx semantic-release

      - name: Sonar scan (Release)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST: ${{ vars.SONAR_HOST }}
          SONAR_ORG: ${{ vars.SONAR_ORG }}
          SONAR_PROJECT_KEY: ${{ vars.SONAR_PROJECT_KEY }}
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

          echo "Running Sonar for release version: $VERSION"

          mvn -B -ntp sonar:sonar \
            -Dsonar.token=${{ env.SONAR_TOKEN }} \
            -Dsonar.host.url=${{ env.SONAR_HOST }} \
            -Dsonar.organization=${{ env.SONAR_ORG }} \
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} \
            -Dsonar.projectVersion=${VERSION} \
            -Dsonar.qualitygate.wait=true